import Navbar from "../components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../lib/Providers";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="max-w-3xl mx-auto">
            <Navbar />
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}